import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { ITreeListItems } from './tree-list.interface';

@Injectable({
  providedIn: 'root'
})
export class TreeListDataService {
  
  selectItems(): Observable<ITreeListItems> {
    return of<ITreeListItems>([
      ...root,
      ...cr,
      ...mb,
      ...sb,
      ...kb,
    ])
  }
}

export const cr: ITreeListItems = [
  {
    id: 8,
    parent_id: 1,
    type: 'folder',
    file_name: 'ФЛ, ЮЛ',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 9,
    parent_id: 1,
    type: 'folder',
    file_name: 'Малый бизнес',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 10,
    parent_id: 1,
    type: 'folder',
    file_name: 'Средний бизнес',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 11,
    parent_id: 1,
    type: 'folder',
    file_name: 'Крупный бизнес',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 12,
    parent_id: 1,
    type: 'file',
    file_name: 'Форма анкеты-заявления',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '3.2 Мб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 13,
    parent_id: 1,
    type: 'file',
    file_name: 'Форма анкеты-заявления 2',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '234.2 Кб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 14,
    parent_id: 1,
    type: 'file',
    file_name: 'Форма анкеты-заявления 3',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '1.6 Кб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  }
];
export const mb: ITreeListItems = [];
export const sb: ITreeListItems = [];
export const kb: ITreeListItems = [
  {
    id: 15,
    parent_id: 2,
    type: 'folder',
    file_name: 'Пустая папка',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 16,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма анкеты-заявления 4',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 17,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма анкеты-заявления 5',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 18,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма анкеты-заявления 6',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 19,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма актуализации данных',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '3.2 Мб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 20,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма согласия ООО Меганом',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '234.2 Кб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 21,
    parent_id: 2,
    type: 'file',
    file_name: 'Форма анкеты-заявления 9',
    file: new Blob(['{ "template_id": 1000 }'], { type: 'application/json' }),
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: '1.6 Кб',
    icon_name: 'file',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  }
];

export const root: ITreeListItems = [
  {
    id: 1,
    parent_id: undefined,
    type: 'folder',
    file_name: 'Формы крупного бизнеса',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  },
  {
    id: 2,
    parent_id: undefined,
    type: 'folder',
    file_name: 'Формы малого бизнеса',
    creator_login: 'SuinovNA1',
    creator_shortname: 'Суинов Н.А.',
    create_at: new Date(),
    modified_login: 'SuinovNA1',
    modified_shortname: 'Суинов Н.А.',
    modified_at: new Date(),
    file_size: undefined,
    icon_name: 'folder',
    icon_class_list: 'svg-icon svg-icon-warning svg-icon-md',
  }
];
